# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Robot Remote Server CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Kept current with https://github.com/nodejs/release#release-schedule
        node-version: [14.x, 16.x, 18.x, 19.x]
        robot-version: [3.2.2, 4.1.3, 5.0, 6.0.1]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }} and Robot Framework ${{ matrix.robot-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        sudo pip install robotframework==${{ matrix.robot-version }}
        npm install
    - run: npm test
      env:
        CI: true
